resolver: lts-21.3
packages:
- '.'
flags:
  aeson-pretty:
    lib-only: true
extra-deps:
- git: https://github.com/space-vacuum/aeson-pretty.git
  commit: 27a3cca66ef4d225b83b57646a279ec9e0c2f970
- base-compat-batteries-0.13.0
- integer-conversion-0.1
- text-iso8601-0.1
- th-abstraction-0.5.0.0
- base-compat-0.13.0